// old/client/components/show/show.component.ts
/**
 * Created by taren on 27-1-2017.
 */
import {Component, OnInit, Input} from "@angular/core";
import {SonarrUtil} from "../../shared/sonarr.util";
import {SonarrSeriesModel} from "../../shared/domain/sonarr-series.model";
import {SonarrService} from "../../shared/sonarr.service";

@Component({
  selector: 'show',
  templateUrl: 'show.component.html'
})
export class Showomponent implements OnInit {

  @Input()
  show: SonarrSeriesModel;

  constructor(private util: SonarrUtil, private sonarr:SonarrService) {
  }

  ngOnInit() {
  }

  getPoster() {
    return this.sonarr.getSeriesUrl(this.show, "poster");
  }

  getEpisodeLabelClass() {
    if (this.show)
      return this.util.calculateEpisodeQuoteColor(this.show.episodeFileCount, this.show.episodeCount, this.show.monitored, this.show.status)
    return null;
  }

  selectShow(show:SonarrSeriesModel){
    this.sonarr.activeShow = show;
  }
}

<div class="serie-general row is-collapse-child" *ngIf="show" [routerLink]="['/series', show.id]" (click)="selectShow(show)">

  <div class="small-8 columns">
    <h6 id="title" class="series-title">{{show.title}}</h6>
    <span id="network" class="label secondary hide">{{show.network}}</span>
    <span id="episodesCount" class="{{getEpisodeLabelClass()}}">{{show.episodeCount}}/{{show.episodeFileCount}}</span>
    <span id="status" class="label success">{{show.status}}</span>
  </div>
  <div class="small-2 columns monitored-indicator">
    <i class="material-icons" *ngIf="show.monitored">bookmark</i>
    <i class="material-icons" *ngIf="!show.monitored">bookmark_border</i>
  </div>
  <div class="small-2">
    <img id="poster" [src]="getPoster()">
  </div>
</div>

// src/components/show/show.component.tsx
import * as React from "react";
import { SonarrSeriesModel } from "../../shared/domain/sonarr-series.model";
import { SonarrService } from "../../shared/sonarr.service";
import { SonarrUtil } from "../../shared/sonarr.util";

export class ShowComponent extends React.Component<{ show: SonarrSeriesModel, enthusiasmLevel?: number }> {
  private sonarr: SonarrService = new SonarrService();
  private util: SonarrUtil = new SonarrUtil();

  getPoster( show: SonarrSeriesModel ) {
    return this.sonarr.getSeriesUrl( show, "poster" );
  }

  getEpisodeLabelClass( show: SonarrSeriesModel ) {
    if ( show ) {
      return this.util.calculateEpisodeQuoteColor( show.episodeFileCount, show.episodeCount, show.monitored, show.status );
    }
    return null;
  }

  render() {
    const show: SonarrSeriesModel = this.props.show || new SonarrSeriesModel( {} );
    return (
      <div className="serie-general row is-collapse-child" onClick={() => this.sonarr.activeShow.setData( show )}>

        <div className="small-8 columns">
          <h3 id="title" className="series-title">{show.title}</h3>
          <span id="network" className="label secondary hide">{show.network}</span>
          <span id="episodesCount" className="{ getEpisodeLabelClass() }">{show.episodeCount}/{show.episodeFileCount}</span>
          <span id="status" className="label success">{show.status}</span>
        </div>
        <div className="small-2 columns monitored-indicator">
          <i className="material-icons">{show.monitored ? 'bookmark' : 'bookmark_border'}</i>
        </div>
        <div className="small-2">
          <img id="poster" src={this.getPoster( show )}/>
        </div>
      </div>

    );
  }
}
