// old/client/routes/series/seriesdetails/series-details.component.ts
import {Component, OnInit} from "@angular/core";
import {Router, ActivatedRoute} from "@angular/router";
import {SonarrService} from "../../../shared/sonarr.service";
import {SonarrSeriesModel} from "../../../shared/domain/sonarr-series.model";
import {SonarrSeriesEpisode} from "../../../shared/domain/sonarr-series-episode.model";
import {SonarrUtil} from "../../../shared/sonarr.util";
import {slideToTop} from "../../../shared/animation.util";

@Component( {
  selector: 'series-details',
  templateUrl: 'series-details.component.html',
  host: {'[@slideToTop]': ''},
  animations: [slideToTop]
})

export class SeriesDetailsComponent implements OnInit {

  activeSeason: number = null;

  episodes: Array<SonarrSeriesEpisode> = [];
  activeShow: number                   = null;

  constructor( private sonarr: SonarrService, private router: Router, private util: SonarrUtil, route: ActivatedRoute ) {
    route.params.subscribe( params => {
      this.activeShow = params[ 'id' ];
    } );
  }

  // Do stuff

  ngOnInit() {
    this.sonarr.getSeries().subscribe( ( resp: Array<SonarrSeriesModel> ) => {
      this.sonarr.activeShow = resp.find( show => show.id == this.activeShow );
      this.getEpisodes();
      this.activeSeason = this.sonarr.activeShow.seasons[ this.sonarr.activeShow.seasons.length - 1 ].seasonNumber;
    } );
    if ( this.show ) {
      this.getEpisodes();
    }
  }

  getEpisodes() {
    this.sonarr.getEpisodesForSeries( this.show.id ).subscribe( episodes => {
      this.episodes = episodes;
    } )
  }

  getEpisodeLabelClass() {
    if ( this.show ) {
      return this.util.calculateEpisodeQuoteColor( this.show.episodeFileCount, this.show.episodeCount, this.show.monitored, this.show.status )
    }
    return null;
  }

  ngOnDestroy() {
    this.sonarr.activeShow = null;
  }

  get show(): SonarrSeriesModel {
    return this.sonarr.activeShow;
  }

  getEpisodesForSeason( seasonNumber: number ) {
    return this.episodes.filter( episode => episode.seasonNumber == seasonNumber );
  }

  getPoster() {
    return this.sonarr.getSeriesUrl( this.show, "poster" );
  }

  getBanner() {
    return this.sonarr.getSeriesUrl( this.show, "banner" );
  }


}

<div class="show" *ngIf="show">
  <div class="banner">
    <img [src]="getBanner()" style="width: 100%; height: auto;">
  </div>
  <div class="row">
    <div class="small-4 show-poster">
      <img [src]="getPoster()"/>
    </div>
    <div class="column small-8 show-info">
      <h2><span id="title">{{show.title}}</span></h2>
      <h6 id="start-year"><i class="fi-social-picasa"></i>Started {{show.firstAired | date}}</h6>
      <h6 id="show-status"><i class="material-icons">play_arrow</i>{{show.status}}</h6>
      <h6>
        <i class="material-icons">collections_bookmark</i><span id="seasons">Seasons {{show.seasonCount}}</span>
        <span id="episodes" class="{{getEpisodeLabelClass()}}">{{show.episodeCount}}/{{show.episodeFileCount}}</span>
      </h6>
      <h6>
        <i class="material-icons">access_time</i>
        <span id="air-time">{{show.airTime}}</span> on
        <span id="network" class="network">{{show.network}}</span>
      </h6>
    </div>
  </div>
  <div class="row">
    <p id="summary" class="summary">{{show.overview}}</p>
  </div>
  <hr>

  <!--a list of episodes will be shown here-->
  <h3>Seasons</h3>
  <ul class="season-select menu expanded">
    <li *ngFor="let season of show.seasons" [class.active]="activeSeason == season.seasonNumber ">
      <a (click)="activeSeason = season.seasonNumber">
        <h3>{{season.seasonNumber}}</h3>
      </a>
    </li>
  </ul>
  <p *ngIf="!episodes || !episodes.length">Loading...</p>
  <episode *ngFor="let item of getEpisodesForSeason(activeSeason)" [episode]="item"></episode>


</div>

// src/components/series-details/series-details.component.tsx
import { DataManagerComponent } from "../core/Data.manager.component";
import { SonarrService } from "../../shared/sonarr.service";
import * as React from "react";
import { SonarrSeriesModel } from "../../shared/domain/sonarr-series.model";
import { Observable } from "rxjs/Observable";
import { Navigation } from "../../shared/Navigation";
import { SeriesEpisodeListComponent } from "./series-episode-list.component";

export class SeriesDetailsComponent extends DataManagerComponent<SonarrSeriesModel | undefined, {}> {

  sonarr: SonarrService = new SonarrService();
  navigation: Navigation = new Navigation();

  getData(): Observable<SonarrSeriesModel | undefined> {
    return this.navigation.getStateAndParams().mergeMap( stateAndParams => {
      if ( stateAndParams.state == 'series' && stateAndParams.params.has( 'showId' ) ) {
        return this.sonarr.getSeries().take( 1 ).map( series => series.find( show => show.id == stateAndParams.params.get( 'showId' ) ) );
      }
      return Observable.of( undefined );

    } );
  }

  getPoster( show: SonarrSeriesModel ) {
    return this.sonarr.getSeriesUrl( show, "poster" );
  }

  getBanner( show: SonarrSeriesModel ) {
    return this.sonarr.getSeriesUrl( show, "banner" );
  }

  render() {
    const show: SonarrSeriesModel | undefined = this.state ? (this.state.data ) : undefined;
    console.log( show );
    if ( show ) {
      return (
        <div className="show">
          <div className="banner">
            <img src={this.getBanner( show )}/>
          </div>
          <div className="row">
            <div className="small-4 show-poster">
              <img src={this.getPoster( show )}/>
            </div>
            <div className="column small-8 show-info">
              <h2><span id="title">{show.title}</span></h2>
              <h6 id="start-year">Started {show.firstAired}</h6>
              <h6 id="show-status"><i className="material-icons">play_arrow</i>{show.status}</h6>
              <h6>
                <i className="material-icons">collections_bookmark</i>
                <span id="seasons">Seasons {show.seasonCount}</span>
                <span id="episodes" className="{getEpisodeLabelClass()}">{show.episodeCount}/{show.episodeFileCount}</span>
              </h6>
              <h6>
                <i className="material-icons">access_time</i>
                <span id="air-time">{show.airTime}</span> on
                <span id="network" className="network">{show.network}</span>
              </h6>
            </div>
          </div>
          <div className="row">
            <p id="summary" className="summary">{show.overview}</p>
          </div>
          <SeriesEpisodeListComponent show={show}/>
        </div>
      );
    }
    return null;
  }
}
