// src/components/episode/episode.component.tsx
import * as React from 'react';
import { SonarrUtil } from "../../shared/sonarr.util";
import { SonarrSeriesEpisode } from "../../shared/domain/sonarr-series-episode.model";
import { Navigation } from "../../shared/Navigation";

export class EpisodeComponent extends React.Component<{ episode: SonarrSeriesEpisode, enthusiasmLevel?: number }> {
  private util: SonarrUtil = new SonarrUtil();
  private navigation: Navigation = new Navigation();

  getSeriesTitle( episode: SonarrSeriesEpisode ) {
    if ( episode.series ) {
      return (
        <a className="series-title"
           onClick={() => this.navigation.setState( 'series', ['showId', episode.series.id] )}>{episode.series.title}</a>
      );
    }
    return null;
  }


  isAirdateBeforeNow() {
    return (this.props && this.props.episode && this.props.episode.airDateUtc && new Date( this.props.episode.airDateUtc ).toISOString() < new Date().toISOString())
  }

  render() {
    const episode: SonarrSeriesEpisode = this.props.episode || new SonarrSeriesEpisode( {} );
    return (
      <div className="episode">
        <div className="row expanded">
          <div className="small-10 columns episode-info">
            {this.getSeriesTitle( episode )}
            <div className="episode-title">
              <span
                className="episodenum">{this.util.formatEpisodeNumer( episode.seasonNumber, episode.episodeNumber )}&nbsp;</span>
              <span className="episodename">{episode.title}</span>
            </div>
            <div className="episode-info">
              {!episode.hasFile ? <span className="label secondary">Missing</span> : <span className="label success">Downloaded</span>}
              &nbsp;<span className="date">{this.isAirdateBeforeNow() ? 'Aired' : 'Airs'} {episode.airDateUtc.toLocaleDateString()}</span>            </div>
          </div>
          <div className="small-2 columns monitored-indicator">
            <i className="material-icons">{episode.monitored ? 'bookmark' : 'bookmark_border'}</i>
          </div>
        </div>
      </div>


    );
  }
}

// old/client/components/episode/episode.component.ts
/**
 * Created by taren on 27-1-2017.
 */

import { Component, OnInit, Input } from '@angular/core';
import { SonarrUtil } from "../../shared/sonarr.util";
import { SonarrService } from "../../shared/sonarr.service";

@Component( {
  selector: 'episode',
  templateUrl: 'episode.component.html'
} )
export class EpisodeComponent implements OnInit {

  @Input()
  episode: any;

  private loading: boolean = false;


  constructor( private util: SonarrUtil, private sonarr: SonarrService ) {
  }

  ngOnInit() {
  }


  getEpisodeNumber() {
    if ( this.episode ) {
      return this.util.formatEpisodeNumer( this.episode.seasonNumber, this.episode.episodeNumber )
    } else {
      return null
    }
  }

  isAirdateBeforeNow() {
    return (this.episode && this.episode.airDateUtc && new Date( this.episode.airDateUtc ).toISOString() < new Date().toISOString())
  }

  toggleEpisodeMonitored() {
    if ( !this.loading ) {
      this.loading           = true;
      this.episode.monitored = !this.episode.monitored;
      this.sonarr.setEpisode( this.episode ).subscribe( resp => {
        this.loading = false;
      }, () => {
        this.episode.monitored = !this.episode.monitored;
        this.loading           = false;
      } )
    }
  }

}

<div class="episode">
  <div class="row">
    <div class="small-10 columns episode-info">
      <a class="series-title" *ngIf="episode?.series?.title" [routerLink]="['/series', episode.seriesId]">{{episode?.series?.title}}</a>
      <div class="episode-title">
        <span class="episodenum">{{getEpisodeNumber()}}</span>
        <span class="episodename">{{episode?.title}}</span>
      </div>
      <div class="episode-info">
        <span *ngIf="!episode.hasFile" class="label secondary">Missing</span>
        <span *ngIf="episode.hasFile" class="label success">Downloaded</span>
        <span class="date">{{isAirdateBeforeNow() ? 'Aired' : 'Airs'}} {{episode.airDateUtc | timeAgo}}</span>
      </div>
    </div>
    <div class="small-2 columns monitored-indicator" (click)="toggleEpisodeMonitored()">
      <i class="material-icons" *ngIf="episode.monitored">bookmark</i>
      <i class="material-icons" *ngIf="!episode.monitored">bookmark_border</i>
    </div>
  </div>
</div>
