// src/components/calendar/Calendar.component.tsx
import { DataManagerComponent } from "../core/Data.manager.component";
import { SonarrService } from "../../shared/sonarr.service";
import * as React from "react";
import { SonarrSeriesEpisode } from "../../shared/domain/sonarr-series-episode.model";
import { EpisodeComponent } from "../episode/episode.component";

export class CalendarComponent extends DataManagerComponent<Array<{ date: Date, episodes: Array<SonarrSeriesEpisode> }>, {}> {

  sonarr: SonarrService = new SonarrService();
  calendar: Array<{ date: Date; episodes: Array<SonarrSeriesEpisode> }>;

  getData() {
    return this.sonarr.getCalendar().map( data => {
      if ( data ) {
        let calendarDates: Array<string>                                                 = [];
        let groupedEpisodes: Array<{ date: Date, episodes: Array<SonarrSeriesEpisode> }> = [];
        //create list of dates where episodes are aired
        data.forEach( episode => {
          if ( calendarDates.indexOf( episode.airDate ) == -1 ) {
            calendarDates.push( episode.airDate )
          }
        } );

        calendarDates.forEach( date => {
          groupedEpisodes.push( {
            date: new Date( date ),
            episodes: data.filter( episode => episode.airDate == date )
          } );
        } );

        return groupedEpisodes;
      }
      return [];
    } );
  }

  render() {
    const calendar: Array<{ date: Date, episodes: Array<SonarrSeriesEpisode> }> = this.state ? this.state.data : [];
    return (
        <div>
          {calendar.map( date => {
            return (
                <div key={date.date.getTime()}>
                  <h3> {date.date.toISOString()} </h3>
                  <div>{date.episodes.map( episode => <EpisodeComponent episode={episode} key={episode.id}/> )}</div>
                </div>
            )
          } )
          }

        </div>
    );
  }
}

// old/client/routes/calendar/calendar.component.ts
import {Component, OnInit} from "@angular/core";
import {SonarrService} from "../../shared/sonarr.service";
import {fadeInOut} from "../../shared/animation.util";
import {SonarrSeriesEpisode} from "../../shared/domain/sonarr-series-episode.model";

@Component( {
  selector: 'my-calendar',
  templateUrl: 'calendar.component.html',
  animations: [ fadeInOut ],
  host: { '[@fadeInOut]': '' }
} )
export class CalendarComponent implements OnInit {

  wanted: any;
  calendar: Array<{date: Date, episodes: Array<SonarrSeriesEpisode>}>;

  constructor( private sonarr: SonarrService ) {
    // Do stuff
  }

  ngOnInit() {
    this.getCalendar();
  }

  getCalendar() {

    this.sonarr.getCalendar().subscribe( ( resp: Array<SonarrSeriesEpisode> ) => {
        if ( resp ) {
          let calendarDates: Array<string>                                               = [];
          let groupedEpisodes: Array<{date: Date, episodes: Array<SonarrSeriesEpisode>}> = [];
          //create list of dates where episodes are aired
          resp.forEach( episode => {
            if ( calendarDates.indexOf( episode.airDate ) == -1 ) {
              calendarDates.push( episode.airDate )
            }
          } );


          calendarDates.forEach( date => {
            groupedEpisodes.push( {
              date: new Date( date ),
              episodes: resp.filter( episode => episode.airDate == date )
            } );
          } );

          this.calendar = groupedEpisodes;
        }
      }
    )
  }

  onlyUnique( value: any, index: number, self: Array<any> ) {
    return self.indexOf( value ) === index;
  };

}

<div class="route-title">
  <h3>Upcoming Episodes</h3>
</div>

<div *ngFor="let date of calendar">
  <h4>{{date.date | date:'fullDate'}}</h4>
  <episode *ngFor="let item of date.episodes" [episode]="item"></episode>
</div>
