// old/client/routes/history/history.component.ts
import { Component, OnInit } from "@angular/core";
import { SonarrService } from "../../shared/sonarr.service";
import { fadeInOut } from "../../shared/animation.util";
import groupBy from "lodash/groupBy";
import sortBy from "lodash/sortBy";

@Component( {
  selector: 'my-history',
  templateUrl: 'history.component.html',
  animations: [ fadeInOut ],
  host: { '[@fadeInOut]': '' }
} )
export class HistoryComponent implements OnInit {

  history: Array<Array<any>>;

  constructor( private sonarr: SonarrService ) {
  }

  ngOnInit() {
    this.getWanted();
  }

  getWanted() {
    this.sonarr.getHistory().subscribe( resp => {
      let data     = groupBy( resp, 'episodeId' );
      this.history = Object.keys( data ).map( ( key: string ) => {
        return data[ key ];
      } );
      this.history = this.history.map( set => sortBy( set, 'id' ) );
//      this.history = reverse( sortBy( this.history, ( set ) => set[ 0 ].id ) );
    } );
  }

  getIconFromEvent( eventType: string ) {
    switch ( eventType ) {
      case 'downloadFolderImported':
        return 'assignment_returned';
      case "episodeFileDeleted":
        return 'delete';
      case "grabbed":
        return 'assignment';
      default:
        return 'assignment_late'
    }
  }

  getNameFromEvent( eventType: string ) {
    switch ( eventType ) {
      case 'downloadFolderImported':
        return 'imported';
      case "episodeFileDeleted":
        return 'deleted';
      case "grabbed":
        return 'grabbed';
      default:
        return eventType
    }
  }

}

<div class="route-title">
  <h3>History</h3>
</div>
<div *ngFor="let items of history;">
  <div class="card">
    <div class="card-divider">
      <h5>{{items[0].series.title}}</h5>
      <h6>{{items[0].episode.title}}</h6>
    </div>
    <div class="card-section">
      <ng-container *ngFor="let item of items; index as index;">
        <div class="label" [class.success]="index == items.length -1 && !item.qualityCutoffNotMet"
             title="{{getNameFromEvent(item.eventType)}} - {{item.date | timeAgo}}">
          <span class="material-icons">{{getIconFromEvent(item.eventType)}}</span>
          {{item.quality.quality.name}}
        </div>
      </ng-container>
    </div>
  </div>
</div>

<!--<div *ngFor="let date of calendar">-->
<!--<h4>{{date.date | date:'fullDate'}}</h4>-->
<!--<episode *ngFor="let item of date.episodes" [episode]="item"></episode>-->
<!--</div>-->


<!--<episode *ngFor="let item of wanted?.records" [episode]="item"></episode>-->

// src/components/history/History.component.tsx
import { DataManagerComponent } from "../core/Data.manager.component";
import { SonarrService } from "../../shared/sonarr.service";
import * as React from "react";
import { EpisodeComponent } from "../episode/episode.component";
import { SonarrHistoryItemModel } from "../../shared/domain/sonarr-history-item.model";

export class HistoryComponent extends DataManagerComponent<Array<SonarrHistoryItemModel>, {}> {

  sonarr: SonarrService = new SonarrService();

  private events: any = {
    "downloadFolderImported": 'Imported',
    "grabbed": 'Grabbed',
    "episodeFileDeleted": 'Deleted',
    "hide": '',
    "downloaded": "downloaded",
    "missing": 'Missing ',
    "toBeAired": '',
    "downloadFailed": 'Failed'
  };

  private classes: any = {
    "downloadFolderImported": 'label success',
    "downloaded": 'label success',
    "grabbed": 'label secondary',
    "episodeFileDeleted": 'label alert',
    "hide": 'hide',
    "missing": 'label secondary',
    "toBeAired": 'tba',
    "downloadFailed": 'label alert'
  };

  getData() {
    return this.sonarr.getHistory();
  }

  getEpisodeInfo( history: SonarrHistoryItemModel ) {
    return (
      <div className="episode-info ">
        <span className="label secondary">{history.quality.quality.name}</span>&nbsp;
        <span className={this.classes[history.eventType]}>{this.events[history.eventType]}</span>&nbsp;
        <span className="date">{history.date.toLocaleDateString()}</span>
      </div>
    );
  }

  render() {
    const episodes: Array<SonarrHistoryItemModel> = this.state ? this.state.data : [];
    return episodes.map( episode => (
        <div key={episode.id}>
          <EpisodeComponent episode={episode.episode} episodeInfo={this.getEpisodeInfo( episode )}>
            {this.getEpisodeInfo( episode )}
          </EpisodeComponent>
        </div>
      )
    );
  }
}
